default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] || '12345' %>
  port: 3307
  host: 127.0.0.1

development:
  <<: *default
  database: images_attach_development

test:
  <<: *default
  database: images_attach_test

production:
  <<: *default
  database: smartphone_shop_production
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>